In [1]:
#Task 1: Array Creation and Properties using NumPy.
import numpy as np

# 1D array of 100 random integers between 1 and 50
array1 = np.random.randint(1, 51, 100)

# 2D array (5,6) filled with ones and converted to integer type
array2 = np.ones((5, 6)).astype(int)

# 1D array of 20 evenly spaced values between 0 and 100
array3 = np.linspace(0, 100, 20)

# 3x3 identity matrix
array4 = np.eye(3)

# Function to print array properties
def print_properties(arr, name):
    print(f"\n{name}")
    print("Array:\n", arr)
    print("Shape:", arr.shape)
    print("Dimensions (ndim):", arr.ndim)
    print("Total elements (size):", arr.size)
    print("Data type (dtype):", arr.dtype)
    print("Item size (bytes):", arr.itemsize)

# Display properties
print_properties(array1, "1D Random Integer Array")
print_properties(array2, "2D Ones Array (Integer)")
print_properties(array3, "Evenly Spaced Array")
print_properties(array4, "3x3 Identity Matrix")


1D Random Integer Array
Array:
 [ 8  4 15 24 30 49 32  3 22 44  9 22  8 14 12 27 50  2 17 42 18 41  8 30
  3 13 32 32 41 11 34 21 34 21  9 11  7 16 16 26  7 38  4 49 25 46 32 40
 35 11 48 22 14 25 16 20  7 16  9  1 14 30 38 45  9 43 49  1 39 46 26 11
 29 22 28 32 46 46 44 17 24 21 23  6 42 24  1 46 25 17 24 10 42 32 35 23
 32 48 10  5]
Shape: (100,)
Dimensions (ndim): 1
Total elements (size): 100
Data type (dtype): int64
Item size (bytes): 8

2D Ones Array (Integer)
Array:
 [[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
Shape: (5, 6)
Dimensions (ndim): 2
Total elements (size): 30
Data type (dtype): int64
Item size (bytes): 8

Evenly Spaced Array
Array:
 [  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]
Shape: (20,)
Dimensions (ndim): 1
Total ele

In [2]:
#Task 2: Memory and Speed Comparison (Python List vs NumPy Array).
import numpy as np
import sys
import time

# Create Python list of 10,000 integers
python_list = list(range(1, 10001))

# Create NumPy array with same integers
numpy_array = np.arange(1, 10001)

# Memory consumption
list_memory = sys.getsizeof(python_list)
array_memory = numpy_array.nbytes

print("Memory Consumption:")
print("Python List Memory:", list_memory, "bytes")
print("NumPy Array Memory:", array_memory, "bytes")

# Create second list and array for addition
python_list2 = list(range(1, 10001))
numpy_array2 = np.arange(1, 10001)

# List addition timing
start_time = time.time()

result_list = [python_list[i] + python_list2[i] for i in range(len(python_list))]

list_time = time.time() - start_time

# NumPy addition timing
start_time = time.time()

result_array = numpy_array + numpy_array2

numpy_time = time.time() - start_time

# Display results
print("\nExecution Time:")
print("Python List Addition Time:", list_time, "seconds")
print("NumPy Array Addition Time:", numpy_time, "seconds")

# Speed comparison
speed_factor = list_time / numpy_time
print("\nNumPy is", speed_factor, "times faster than Python lists")

Memory Consumption:
Python List Memory: 80056 bytes
NumPy Array Memory: 80000 bytes

Execution Time:
Python List Addition Time: 0.0016527175903320312 seconds
NumPy Array Addition Time: 0.00046634674072265625 seconds

NumPy is 3.5439672801635993 times faster than Python lists


In [3]:
#Task 3: Practical Application (Sales Data Simulation).
import numpy as np

# Generate sales data: 30 days × 4 products
sales_data = np.random.randint(100, 1001, size=(30, 4))

print("Sales Data:\n", sales_data)

# 1. Total sales for each product (column-wise sum)
product_total_sales = np.sum(sales_data, axis=0)
print("\nTotal Sales for Each Product:", product_total_sales)

# 2. Average daily sales across all products (row-wise mean)
daily_average_sales = np.mean(sales_data, axis=1)
print("\nAverage Daily Sales:", daily_average_sales)

# 3. Day with maximum total sales
daily_totals = np.sum(sales_data, axis=1)
max_sales_day = np.argmax(daily_totals)

print("\nDay with Maximum Total Sales:", max_sales_day + 1)
print("Maximum Sales Value:", daily_totals[max_sales_day])

# 4. Product with minimum average sales
product_avg_sales = np.mean(sales_data, axis=0)
min_avg_product = np.argmin(product_avg_sales)

print("\nProduct with Minimum Average Sales:", min_avg_product + 1)
print("Average Sales:", product_avg_sales[min_avg_product])

# 5. Convert integers to float32 to optimize memory
sales_float32 = sales_data.astype(np.float32)

print("\nOriginal Data Type:", sales_data.dtype)
print("New Data Type:", sales_float32.dtype)

# Memory comparison per element
original_itemsize = sales_data.itemsize
new_itemsize = sales_float32.itemsize

memory_saved = original_itemsize - new_itemsize

print("\nOriginal Memory per Element:", original_itemsize, "bytes")
print("New Memory per Element:", new_itemsize, "bytes")
print("Memory Saved per Element:", memory_saved, "bytes")

Sales Data:
 [[966 215 234 990]
 [857 284 999 913]
 [879 258 616 641]
 [954 906 369 180]
 [988 800 277 325]
 [911 766 102 580]
 [628 805 105 150]
 [331 977 710 889]
 [691 326 569 355]
 [670 130 152 523]
 [324 704 439 423]
 [843 878 459 481]
 [190 637 400 857]
 [502 112 438 182]
 [821 822 124 433]
 [909 627 717 451]
 [420 337 205 414]
 [110 310 551 803]
 [294 973 787 346]
 [657 206 616 401]
 [693 659 760 136]
 [705 824 981 137]
 [610 982 255 450]
 [887 287 639 867]
 [157 708 314 264]
 [974 288 661 314]
 [658 564 694 367]
 [106 582 532 340]
 [599 654 739 170]
 [641 639 166 784]]

Total Sales for Each Product: [18975 17260 14610 14166]

Average Daily Sales: [601.25 763.25 598.5  602.25 597.5  589.75 422.   726.75 485.25 368.75
 472.5  665.25 521.   308.5  550.   676.   344.   443.5  600.   470.
 562.   661.75 574.25 670.   360.75 559.25 570.75 390.   540.5  557.5 ]

Day with Maximum Total Sales: 2
Maximum Sales Value: 3053

Product with Minimum Average Sales: 4
Average Sales: 472.2

Origi